###############################################
# AMCL (Localization)
###############################################

amcl:
  ros__parameters:

    use_sim_time: False              # 실제 로봇이므로 False
    robot_model_type: "nav2_amcl::DifferentialMotionModel" #  두 개의 구동 바퀴로 움직이는 차륜형 로봇(Differential Drive). 옴니휠 경우 nav2_amcl::OmniMotionModel
    base_frame_id: "base_link"       # 로봇 기준 프레임
    odom_frame_id: "odom"            # 오도메트리 프레임
    global_frame_id: "map"           # 맵 기준 프레임

    scan_topic: scan                 # LiDAR topic scan_fixed -> scan 20260312
    tf_broadcast: True               # AMCL이 map→odom TF 발행

    # 파티클 필터 개수 (정확도 vs CPU) ,입자 수 너무 적으면 위치 불안정(점프), 너무 많으면 CPU 부담
    min_particles: 500
    max_particles: 2000

    # 위치 업데이트 조건
    # update_min_d: 0.10               # 10cm 이동 시 업데이트
    # update_min_a: 0.10               # 약 10도 회전 시 업데이트
    # 🔥 업데이트 민감도 (더 자주 갱신)
    # update_min_d: 0.1 #05
    # update_min_a: 0.1 # 05
    
    update_min_d: 0.05               # 5cm 이동 시 업데이트
    update_min_a: 0.05               # 약 5도 회전 시 업데이트

    transform_tolerance: 0.5         # TF 지연 허용

    # ⭐⭐⭐ 핵심 AMCL 안정화 매개변수 ⭐⭐⭐ 합이 1.0이 되도록 조정
    laser_z_hit: 0.7        # 레이저가 실제 장애물에 맞을 확률 (0.9로 높여서 센서 신뢰도 증가) 라이다 매칭 신뢰도 0.9-> 0.7 
    laser_z_short: 0.1      # 레이저가 예상보다 짧게 측정될 확률 (0.1로 낮춰서 이상치 영향 감소) 라이다 이상치 (예: 투명 유리) 영향 감소
    laser_z_max: 0.05       # 레이저가 최대 범위를 초과할 확률 (0.05로 낮춰서 센서 노이즈 영향 감소) 라이다 노이즈 영향 감소
    laser_z_rand: 0.15       # 레이저가 무작위로 측정될 확률 (0.1로 낮춰서 센서 노이즈 영향 감소) 라이다 랜덤 노이즈 영향 감소, 랜덤 노이즈 :너무 크면 수렴 느림   0.1-> 0.15

    laser_sigma_hit: 0.2    # 레이저 측정의 표준 편차 (0.2로 낮춰서 센서 신뢰도 증가) 라이다 측정 신뢰도 증가 , 센서 오차 너무크면 위치 퍼짐?

    resample_interval: 1    # 재샘플링 간격 (1로 줄여서 더 자주 재샘플링) 파티클 필터 안정성 증가

    # 잘못된 위치를 감지하고 파티클을 다시 뿌리는 강도
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    max_beams: 60  # 기본값(30)보다 늘려서 더 촘촘하게 맵을 비교하게 함

    initial_cov_xx: 1.0
    initial_cov_yy: 1.0
    initial_cov_aa: 0.5

    set_initial_pose: true  # 혹은 false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
###############################################
# Behavior Tree Navigator
###############################################

bt_navigator:
  ros__parameters:

    use_sim_time: False

    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom

    # Nav2 기본 행동 트리
    default_bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"



###############################################
# Global Planner
###############################################

planner_server:
  ros__parameters:

    use_sim_time: False
    expected_planner_frequency: 20.0      # 플래너가 Hz로 경로를 갱신 (낮추면 CPU 부담 감소, 높이면 더 자주 갱신) 
    planner_plugins: ["GridBased"]
    
    GridBased:

      # SMAC Planner (A* 개선형)
      plugin: "nav2_smac_planner::SmacPlanner2D"

      tolerance: 0.25                # 목표 근처 허용 오차
      allow_unknown: false #True            # unknown 영역 통과 허용 ,false: 검은색 영역을 "갈 수 없는 곳"으로 엄격하게 제한

      downsample_costmap: false      # Costmap 해상도 그대로 사용
      use_grid_path: true            # 그리드 기반 경로 생성 (false는 스플라인)
      cost_travel_multiplier: 5.0      # cost_travel_multiplier: 1.0     # 이동 비용 가중치 (기본값 1.0, 높이면 더 안전한 경로 선호)
      use_quadratic_cost_penalty: true # 장애물 근처에서 비용이 더 빠르게 증가하도록 설정 (기본값 false)

      max_iterations: 100000         # 탐색 최대 반복
      max_on_approach_iterations: 1000



###############################################
# Local Controller
###############################################

controller_server:
  ros__parameters:

    use_sim_time: false

    use_realtime_priority: false
    
    controller_frequency: 20.0       # 제어 루프 (Hz)

    #################################
    # Progress checker
    #################################

    progress_checker_plugins: ["progress_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10     # 10cm 이동
      movement_time_allowance: 5.0       # 5초 안에 이동 못하면 실패


    #################################
    # Controller plugin
    #################################

    controller_plugins: ["FollowPath"]

    FollowPath:

      # Pure Pursuit Controller (산업용에서 많이 사용)
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      #################################
      # 속도 설정
      #################################

      desired_linear_vel: 0.20  #0.25       # 목표 속도  평소 desired_linear_vel 달리다가 최대 max_vel_x 로 달림

      max_vel_x: 0.22 #0.15 #0.22              # 최대 전진 속도
      min_vel_x: 0.1 #-0.05                 # 후진 

      max_vel_theta: 1.5             # 최대 회전 속도
      min_speed_theta: 0.7           # 최소 회전 속도

      #################################
      # 가속 제한
      #################################

      acc_lim_x: 0.8
      decel_lim_x: -0.8

      acc_lim_theta: 2.0
      decel_lim_theta: -2.0


      #################################
      # 예측 시간
      #################################

      sim_time: 1.5                  # 1.5초 미래 예측


      #################################
      # TF 지연 허용
      #################################

      transform_tolerance: 0.2

      # 🔥 좁은길 안정성
      use_collision_detection: true
      regulate_linear_velocity: true

      # 🔥 벽 접근 시 감속
      cost_scaling_dist: 0.4
      cost_scaling_gain: 1.0

      #################################
      # 속도 샘플 개수
      #################################
      # RegulatedPurePursuitController 에서는 사용 안함
      # vx_samples: 10
      # vtheta_samples: 40             # CPU 여유 있으면 40


      #################################
      # 옴니 로봇용 (차동이면 영향 거의 없음)
      #################################

      # min_speed_xy: 0.0
      # max_speed_xy: 0.22
      # min_speed_theta: 0.0


      #################################
      # Goal checker
      #################################

      goal_checker_plugins: ["goal_checker"]

      goal_checker:

        plugin: "nav2_controller::SimpleGoalChecker"

        stateful: True
        xy_goal_tolerance: 0.15      # 목표 위치 오차
        yaw_goal_tolerance: 0.2      # 목표 방향 오차


###############################################
# Local Costmap
###############################################

local_costmap:
  local_costmap:
    ros__parameters:
      # footprint: "[[0.16,0.16],[0.16,-0.16],[-0.16,-0.16],[-0.16,0.16]]"
      footprint: "[[0.20,0.16],[0.20,-0.16],[-0.20,-0.16],[-0.20,0.16]]"
      # footprint: "[[0.30,0.30],[0.30,-0.30],[-0.30,-0.30],[-0.30,0.30]]"
# 앞  +0.20m
# 뒤  -0.20m

# 좌  +0.16m
# 우  -0.16m

      #            y
      #      ↑
      # (-0.25,0.18) -------- (0.15,0.15)
      #      |                    |
      #      |        ●           |
      #      |     robot center   |
      #      |                    |
      # (-0.25,-0.18) ------- (0.15,-0.15)
      #                    → x

      use_sim_time: False

      # update_frequency: 30.0   # 최소 10 이상 추천      
      update_frequency: 3.0  # 👈 코스트맵 업데이트 주기를 3~5Hz로 제한
      publish_frequency: 2.0 # 👈 코스트맵 시각화 토픽 발행 주기를 2Hz로 제한

      global_frame: odom #odom -> base_link 20260321 -> odom 20260324
      robot_base_frame: base_footprint  #base_link -> base_footprint 20260509 ,base_link는 3D 움직임 일때 사용( 드론)

      rolling_window: True           # 로봇 중심 이동 창

      width: 5
      height: 5

      resolution: 0.05               # costmap 해상도

      robot_radius: 0.16             # 로봇 반지름

      plugins:
        - obstacle_layer
        # - human_layer 
        - inflation_layer
        - voxel_layer
  
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true

        origin_z: 0.0
        # z_resolution: 0.05
        # z_voxels: 16
        z_resolution: 0.1        # ← 기존 0.05 → 0.1 (성능 + 안정)
        z_voxels: 10             # ← 줄임

        max_obstacle_height: 1.5
        # min_obstacle_height: 0.05
        min_obstacle_height: 0.1  # ← 바닥 노이즈 제거 핵심

        observation_sources: depth

        depth:
          topic: /camera/depth/points
          data_type: "PointCloud2"
          marking: true
          clearing: true

      #################################
      # Obstacle Layer
      #################################

      obstacle_layer:
        enabled: true
        plugin: "nav2_costmap_2d::ObstacleLayer"

        observation_sources: "scan "

        scan:

          topic: /scan                
          data_type: "LaserScan"

          clearing: true
          marking: true

          # qos_overrides:
          #   reliability: best_effort

          # obstacle_min_range: 0.20
          obstacle_max_range: 2.5     # 2.5m까지 장애물 생성

          raytrace_min_range: 0.20
          raytrace_max_range: 3.0

          inf_is_valid: true

          min_obstacle_height: -0.5  # 바닥보다 낮게 잡아 여유를 둠
          max_obstacle_height: 2.0   # 로봇 키보다 높게 설정

          observation_persistence: 3.0   # 관측 유지 시간 (초) , 1.0으로 늘려서 장애물 흔적 더 오래 유지, 너무 길면 오래된 장애물 남아있음



        depth:

          topic: /scan_depth
          data_type: "LaserScan"

          clearing: true
          marking: true

          obstacle_max_range: 2.5     # 2.5m까지 장애물 생성

          raytrace_min_range: 0.20
          raytrace_max_range: 2.0

          inf_is_valid: true

          min_obstacle_height: -0.5  # 바닥보다 낮게 잡아 여유를 둠
          max_obstacle_height: 2.0   # 로봇 키보다 높게 설정

          observation_persistence: 3.0   # 관측 유지 시간 (초) , 1.0으로 늘려서 장애물 흔적 더 오래 유지, 너무 길면 오래된 장애물 남아있음   

      #################################
      # Inflation Layer
      #################################

      inflation_layer:

        plugin: "nav2_costmap_2d::InflationLayer"

        inflation_radius: 0.3       # 장애물 영향 반경 # ← 이거 크면 길 다 막힘
        cost_scaling_factor: 5.0     # 장애물 주변의 “위험도 증가 속도, 낮을수록 벽 멀리 회피

        transform_tolerance: 1.0
        always_send_full_costmap: false   # 🔥 이거 추가
# | inflation_radius | cost_scaling_factor | 결과    |
# | ---------------- | ------------------- | ----- |
# | 작음              | 큼                   | 벽 가까이 |
# | 큼                | 작음                 | 벽 멀리  |
# | 큼                | 큼                  | 자연    |
# | 작음              | 작음                 | 이상함   |

      # human_layer:
      #   plugin: "human_n_obstacle_layer::HumanLayer"



###############################################
# Global Costmap
###############################################

global_costmap:
  global_costmap:
    ros__parameters:

      use_sim_time: False

      update_frequency: 5.0   # 최소 5 이상 추천

      global_frame: map
      robot_base_frame: base_footprint  #base_link

      resolution: 0.05

      rolling_window: False           # 로봇 중심 이동 창


      track_unknown_space: true #False

      robot_radius: 0.16

      plugins:
        - static_layer
        # - human_layer
        - obstacle_layer
        - inflation_layer
      #################################
      # Static map layer
      #################################

      static_layer:

        plugin: "nav2_costmap_2d::StaticLayer"

        map_subscribe_transient_local: True


      #################################
      # Inflation layer
      #################################

      inflation_layer:

        plugin: "nav2_costmap_2d::InflationLayer"

        inflation_radius: 0.3        # 장애물 영향 반경 # ← 이거 크면 길 다 막힘
        cost_scaling_factor: 5.0     # 장애물 주변의 “위험도 증가 속도, 낮을수록 벽 멀리 회피

        transform_tolerance: 1.0
        always_send_full_costmap: false #<------------true?
        # False (기본값): 코스트맵에서 변화가 생긴 부분(업데이트된 영역)만 패치 형태로 보냅니다. 네트워크 대역폭을 아낄 수 있어 효율적입니다.True: 변화 여부와 상관없이 전체 지도 데이터를 매번 통째로 보냅니다. 
        # 네트워크 대역폭이 충분하다면 전체 코스트맵을 보내는 것이 최신 상태를 유지하는 데 도움이 될 수 있습니다. 특히, 코스트맵이 자주 변경되거나 업데이트 영역이 넓은 경우에는 전체 코스트맵을 보내는 것이 안정적인 경로 계획에 유리할 수 있습니다.

      # human_layer:
      #   plugin: "human_n_obstacle_layer::HumanLayer"

      obstacle_layer:
        enabled: true
        plugin: "nav2_costmap_2d::ObstacleLayer"

        observation_sources: scan
        
        scan:

          topic: /scan                
          data_type: "LaserScan"

          clearing: True
          marking: True

          # qos_overrides:
          #   reliability: best_effort

          # obstacle_min_range: 0.20
          obstacle_max_range: 2.5     # 2.5m까지 장애물 생성

          raytrace_min_range: 0.20
          raytrace_max_range: 3.0

          inf_is_valid: true

          min_obstacle_height: -0.5  # 바닥보다 낮게 잡아 여유를 둠
          max_obstacle_height: 2.0   # 로봇 키보다 높게 설정

          observation_persistence:  3.0   # 관측 유지 시간 (초) , 1.0으로 늘려서 장애물 흔적 더 오래 유지, 너무 길면 오래된 장애물 남아있음
# ###############################################
# # Velocity smoother
# ###############################################

# velocity_smoother:
#   ros__parameters:

#     use_sim_time: False

#     smoothing_frequency: 20.0

#     scale_velocities: False

#     max_velocity: [0.22, 0.0, 2.0]
#     min_velocity: [0.0, 0.0, -2.0]

#     max_accel: [0.8, 0.0, 2.0]
#     max_decel: [-0.8, 0.0, -2.0]

#     odom_topic: /odom
#     odom_duration: 0.1

#     deadband_velocity: [0.0, 0.0, 0.0]

#     velocity_timeout: 1.0



###############################################
# Collision Monitor
###############################################
# collision_monitor:
#   ros__parameters:

#     use_sim_time: False

#     base_frame_id: base_footprint
#     odom_frame_id: odom

#     cmd_vel_in_topic: cmd_vel
#     cmd_vel_out_topic: cmd_vel

#     state_topic: collision_monitor_state

#     transform_tolerance: 0.5

#     observation_sources: ["scan"]

#     scan:
#       type: scan
#       topic: /scan
#       min_obstacle_dist: 0.30
#       max_obstacle_dist: 2.5

#     polygons: ["footprint"]

#     footprint:
#       type: polygon
#       action_type: stop
#       points: "[[0.25,0.18],[0.25,-0.18],[-0.25,-0.18],[-0.25,0.18]]"

      #            y
      #      ↑
      # (-0.25,0.18) -------- (0.25,0.18)
      #      |                    |
      #      |        ●           |
      #      |     robot center   |
      #      |                    |
      # (-0.25,-0.18) ------- (0.25,-0.18)
      #                    → x


# lifecycle_manager_navigation:
#   ros__parameters:
#     use_sim_time: False
#     autostart: true
#     node_names:
#       - map_server
#       - amcl
#       - planner_server
#       - controller_server
#       - behavior_server
#       - bt_navigator