usb_cam:
  ros__parameters:
    video_device: "/dev/video0"

    image_width: 320
    image_height: 240
    framerate: 15.0

    pixel_format: "mjpeg2rgb"
    io_method: "mmap"

    frame_id: "camera_link"

    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1

    auto_white_balance: true
    autoexposure: true
